name: Mobile CI (Policía de React Native)

# Se activa solo cuando tocáis la carpeta 'mobile'
on:
  push:
    branches: [ "main" ]
    paths:
      - 'mobile/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mobile/**'

jobs:
  mobile-check:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./mobile

    steps:
    # 1. Bajar código
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Preparar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json

    # 3. Instalar librerías
    - name: Install dependencies
      run: npm ci

    # 4. Linting (Revisa que el código esté limpio y sin errores de sintaxis)
    - name: Lint Check
      run: npm run lint

    # 5. Tests (Ejecuta Jest para asegurar que la lógica funciona)
    - name: Run Tests
      run: npm test